name: GitHub Readme YouTube Cards
on:
  schedule:
    # A las 12:00 AM, solo los viernes
    - cron: "0 0 * * VIE*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: prNZN41Ah3XSoAxea2Wozw